### ISSUE TITLE
Package import does not work after installing via npm

### ISSUE THREAD

**Issue by SujitGadkari** [ExpediaGroup/fpsmeter#2]
### Description

Trying to import the '@vrbo/fpsmeter' package does not work after installing the package correctly either as dependency or devdependency.

### Steps to Reproduce

1. `npm install --save @vrbo/fpsmeter`
2. `import FPSMeter from '@vrbo/fpsmeter';` as described in README
3. Notice that the package is not recognized by the IDE (Atom in my case) and webpack build also cannot find/identify the package resulting in 'package not found' error.

Development environment used for this test:
node: v10.15.3
npm: 6.4.1
OSX: 10.14.6 (Mojave)

**Expected behavior:** [What you expected to happen]
Package works as described in README and recognized by build process as well as IDE

**Actual behavior:** [What actually happened]
Package is not recognized in spite of being available under 'node_modules' of the project where it's installed.

### Versions
V1.0.0

### Other Comments
I believe this is happening because of package being published incorrectly as the package directory in 'node_modules' seems to be missing any obvious entry points.

I was able to get this working locally by cloning the repo, running 'npm run build' task and then using 'npm link' to link this local repo with my project where I am trying to test this package.

**Comment by neenhouse** [comment]
@SujitGadkari - Thanks for reporting this issue.

Merge spam was due to a configuration issue with Travis.  `1.0.0` was shipped through previously misconfigured auto publish that would clear the lib directory. `1.0.1` is released as a patch fix to include lib.

The CI now implements `semantic-release` for more complete release automation.

Tested and verified locally installed `1.0.1` version now actually includes lib.
